### ISSUE TITLE
Refuse connect problems

### ISSUE THREAD

**Issue by tungdo0602** [doggybootsy/discord-hacks#5]
![image](https://user-images.githubusercontent.com/89498812/150688967-1f73fd40-b020-48d0-a67a-726c2f45786c.png)
it there a way to bypass/skip this on discord web?

**Comment by doggybootsy** [comment]
There are many extensions (for all browsers) that allow you to bypass csp

**Comment by tungdo0602** [comment]
hmm

**Comment by tungdo0602** [comment]
can u give me a script :D

**Comment by tungdo0602** [comment]
i have try some csp disabler and try to disable csp in firefox but when i trying to fetch it still have errors

**Comment by tungdo0602** [comment]
it like missing the csp headers

**Comment by doggybootsy** [comment]
> can u give me a script :D

unfortunately js cant without the extension context
> i have try some csp disabler and try to disable csp in firefox but when i trying to fetch it still have errors

Strange

**Comment by tungdo0602** [comment]
hmm
